# PATH setup for Homebrew and MacTeX
fish_add_path /opt/homebrew/bin
fish_add_path /opt/homebrew/sbin
fish_add_path /usr/local/texlive/2025/bin/universal-darwin

# host-specific configs
set host (hostname)
set host_config ~/.config/fish/conf.d/hostname-$host.fish
if test -f $host_config
    source $host_config
end

# Theme: ~/.config/fish/conf.d/colors.fish is auto-generated by theme-apply
# and auto-sourced by fish. No theme orchestration needed here.

# Suppress fish's automatic terminal title (tmux owns titles).
function fish_title; end

# bash-esque aliases
function vi; nvim $argv; end
function vim; nvim $argv; end
function l; ls -la; end
function tsc; source /Users/matter/coldtype/typesoundcode.feb2025/.venv/bin/activate.fish; end

# use startship for prompt
starship init fish | source
# starship preset gruvbox-rainbow -o ~/.config/starship.toml
# starship preset no-runtime-versions -o ~/.config/starship.toml

# XDG base dirs (lazygit & other XDG-aware tools read config from here)
set -gx XDG_CONFIG_HOME $HOME/.config

# set editor, mostly for lazygit but probably other stuff
set -gx EDITOR nvim

# Claude Code downgrades to 256-color inside tmux by default; opt back into 24-bit
# so its theme matches nvim (COLORTERM=truecolor provides the base level).
set -gx CLAUDE_CODE_TMUX_TRUECOLOR 1

# Ollama API base URL for aider
set -gx OLLAMA_API_BASE http://localhost:11434

# Audio plugin directories
set -gx VST3_USER_DIR ~/Library/Audio/Plug-Ins/VST3
set -gx VST3_SYSTEM_DIR /Library/Audio/Plug-Ins/VST3
set -gx AU_USER_DIR ~/Library/Audio/Plug-Ins/Components
set -gx AU_SYSTEM_DIR /Library/Audio/Plug-Ins/Components
set -gx CLAP_USER_DIR ~/Library/Audio/Plug-Ins/CLAP
set -gx CLAP_SYSTEM_DIR /Library/Audio/Plug-Ins/CLAP

source ~/.secrets.fish

# Load SSH key from keychain if the agent is empty (git commit signing)
ssh-add -l > /dev/null 2>&1; or ssh-add --apple-load-keychain > /dev/null 2>&1
