# Host-specific config: PATH, OS-specific env, machine-local aliases.
# Lives in hosts/ rather than conf.d/ because fish auto-sources *every* file in
# conf.d/ — so a host file there loads on every machine, not just its own, and
# loads twice on its own (once by conf.d, once by the source below).
set host (hostname)
set host_config $__fish_config_dir/hosts/$host.fish
if test -f $host_config
    source $host_config
end

# Theme: ~/.config/fish/conf.d/colors.fish is auto-generated by theme-apply
# and auto-sourced by fish. No theme orchestration needed here.

# Suppress fish's automatic terminal title (tmux owns titles).
function fish_title; end

# bash-esque aliases
function vi; nvim $argv; end
function vim; nvim $argv; end
function l; ls -la; end

# use startship for prompt
# starship defaults to ~/.config/starship.toml. Point it at the copy tracked in
# this repo instead, so a new machine gets the prompt by cloning the config —
# no per-host symlink to remember. Must precede `starship init`, which runs the
# binary. The preset lines below write through the same variable; aimed at the
# default path they would silently produce a file starship no longer reads.
set -gx STARSHIP_CONFIG $__fish_config_dir/starship.toml

starship init fish | source
# starship preset gruvbox-rainbow -o $STARSHIP_CONFIG
# starship preset no-runtime-versions -o $STARSHIP_CONFIG

# XDG base dirs (lazygit & other XDG-aware tools read config from here).
# Only set a default — overwriting an explicit value breaks running this config
# against an alternate config root, which is how it gets tested in isolation.
set -q XDG_CONFIG_HOME; or set -gx XDG_CONFIG_HOME $HOME/.config

# set editor, mostly for lazygit but probably other stuff
set -gx EDITOR nvim

# Claude Code downgrades to 256-color inside tmux by default; opt back into 24-bit
# so its theme matches nvim (COLORTERM=truecolor provides the base level).
set -gx CLAUDE_CODE_TMUX_TRUECOLOR 1

# Ollama API base URL for aider
set -gx OLLAMA_API_BASE http://localhost:11434

# Machine-local secrets are optional — not every host has this file, and a bare
# `source` on a missing file errors on every shell start.
test -f ~/.secrets.fish; and source ~/.secrets.fish
