format = """
$battery\
$username\
$hostname\
$directory\
$git_branch $git_state$git_status \
$cmd_duration\
$line_break\
$character"""

[directory]
read_only = ""

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = """\
\\[[[($conflicted)](red)\
[($untracked)](green)\
[($modified)](blue)\
[($staged)](yellow)\
[($renamed)](blue)\
[($deleted)](red)]($style)\
\\]($ahead_behind$stashed)"""
style = "orange"
conflicted = "!"
untracked = "+"
modified = "~"
staged = "/"
renamed = "="
deleted = "-"
stashed = "^"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[character]
success_symbol = "¬"
error_symbol = " ¬"
vimcmd_symbol = ">"
vimcmd_replace_one_symbol = "r"
vimcmd_replace_symbol = "R"
vimcmd_visual_symbol = "v"
