# Auto-generated by theme-apply from base16-gruvbox-dark-medium — do not edit manually
# Fish syntax-highlighting colors keyed to the base16 palette.

set -g fish_color_normal       d5c4a1
set -g fish_color_command      d3869b
set -g fish_color_keyword      d3869b
set -g fish_color_end          d3869b
set -g fish_color_quote        b8bb26
set -g fish_color_redirection  8ec07c
set -g fish_color_escape       8ec07c
set -g fish_color_operator     8ec07c
set -g fish_color_param        83a598
set -g fish_color_option       83a598
set -g fish_color_comment      fabd2f
set -g fish_color_error        fb4934
set -g fish_color_autosuggestion 665c54 --italics
set -g fish_color_search_match --background=665c54
set -g fish_color_selection    --background=665c54

# Export base16 palette so anything that read $color00..15 (e.g. starship templates) still works.
set -gx BASE16_THEME gruvbox-dark-medium
set -gx color00 282828
set -gx color01 fb4934
set -gx color02 b8bb26
set -gx color03 fabd2f
set -gx color04 83a598
set -gx color05 d3869b
set -gx color06 8ec07c
set -gx color07 d5c4a1
set -gx color08 665c54
set -gx color09 fb4934
set -gx color10 b8bb26
set -gx color11 fabd2f
set -gx color12 83a598
set -gx color13 d3869b
set -gx color14 8ec07c
set -gx color15 fbf1c7
